---
- name: 'Instala MySQL Server'
  apt:
    name: mysql-server
    state: latest
  become: yes

- name: 'Instala Python Mysqldb'
  apt:
    name: python3-mysqldb
    state: latest
  become: yes

- name: 'Cria o banco do MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes

- name: 'Cria o usuário do MySQL'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    update_password: on_create
    host: "{{ item }}"
  with_items:
    - "{{ wp_host_ip }}"
  become: yes

- name: 'Configura MySQL para aceitar conexões remotas'
  copy:
    src: '/vagrant/configs/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
    remote_src: yes
  become: yes
  notify:
    - restart mysql
